// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Paper.Web.Data;

#nullable disable

namespace Paper.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006215407_MailImportState")]
    partial class MailImportState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Paper.Web.Data.Correspondent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Correspondents", null, t =>
                        {
                            t.HasCheckConstraint("CK_Correspondents_Name", "length(trim(\"Name\")) > 0");
                        });
                });

            modelBuilder.Entity("Paper.Web.Data.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CorrespondentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DocumentDate")
                        .HasColumnType("date");

                    b.Property<long?>("DocumentTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OcrError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("OcrStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("OcrText")
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "german")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "SearchText" });

                    b.Property<long?>("ShelfFolderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CorrespondentId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("ShelfFolderId");

                    b.HasIndex("Status", "UpdatedAt");

                    b.ToTable("Documents", null, t =>
                        {
                            t.HasCheckConstraint("CK_Documents_FileSize", "\"FileSize\" >= 0");

                            t.HasCheckConstraint("CK_Documents_Title", "length(trim(\"Title\")) > 0");
                        });
                });

            modelBuilder.Entity("Paper.Web.Data.DocumentTag", b =>
                {
                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint");

                    b.HasKey("DocumentId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("DocumentTags", (string)null);
                });

            modelBuilder.Entity("Paper.Web.Data.DocumentType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DocumentTypes", null, t =>
                        {
                            t.HasCheckConstraint("CK_DocumentTypes_Name", "length(trim(\"Name\")) > 0");
                        });
                });

            modelBuilder.Entity("Paper.Web.Data.MailImportState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastUid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccountName")
                        .IsUnique();

                    b.ToTable("MailImportStates", null, t =>
                        {
                            t.HasCheckConstraint("CK_MailImportStates_LastUid", "\"LastUid\" >= 0");
                        });
                });

            modelBuilder.Entity("Paper.Web.Data.ProcessingJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "Type", "State");

                    b.HasIndex("State", "Priority", "CreatedAt");

                    b.ToTable("ProcessingJobs", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProcessingJobs_Attempts", "\"Attempts\" >= 0");

                            t.HasCheckConstraint("CK_ProcessingJobs_Priority", "\"Priority\" >= 0");
                        });
                });

            modelBuilder.Entity("Paper.Web.Data.ShelfFolder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RelativePath")
                        .IsUnique();

                    b.HasIndex("ParentId", "Name")
                        .IsUnique();

                    b.ToTable("ShelfFolders", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShelfFolders_Name", "length(trim(\"Name\")) > 0");

                            t.HasCheckConstraint("CK_ShelfFolders_RelativePath", "length(trim(\"RelativePath\")) > 0");
                        });
                });

            modelBuilder.Entity("Paper.Web.Data.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tags_Name", "length(trim(\"Name\")) > 0");
                        });
                });

            modelBuilder.Entity("Paper.Web.Features.CustomFields.CustomField", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CustomFields", null, t =>
                        {
                            t.HasCheckConstraint("CK_CustomFields_Name", "length(trim(\"Name\")) > 0");
                        });
                });

            modelBuilder.Entity("Paper.Web.Features.CustomFields.DocumentCustomFieldValue", b =>
                {
                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("CustomFieldId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("DocumentId", "CustomFieldId");

                    b.HasIndex("CustomFieldId");

                    b.ToTable("DocumentCustomFieldValues", (string)null);
                });

            modelBuilder.Entity("Paper.Web.Data.Document", b =>
                {
                    b.HasOne("Paper.Web.Data.Correspondent", "Correspondent")
                        .WithMany("Documents")
                        .HasForeignKey("CorrespondentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Paper.Web.Data.DocumentType", "DocumentType")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Paper.Web.Data.ShelfFolder", "ShelfFolder")
                        .WithMany("Documents")
                        .HasForeignKey("ShelfFolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Correspondent");

                    b.Navigation("DocumentType");

                    b.Navigation("ShelfFolder");
                });

            modelBuilder.Entity("Paper.Web.Data.DocumentTag", b =>
                {
                    b.HasOne("Paper.Web.Data.Document", "Document")
                        .WithMany("Tags")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paper.Web.Data.Tag", "Tag")
                        .WithMany("Documents")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Paper.Web.Data.ProcessingJob", b =>
                {
                    b.HasOne("Paper.Web.Data.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Paper.Web.Data.ShelfFolder", b =>
                {
                    b.HasOne("Paper.Web.Data.ShelfFolder", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Paper.Web.Features.CustomFields.DocumentCustomFieldValue", b =>
                {
                    b.HasOne("Paper.Web.Features.CustomFields.CustomField", "CustomField")
                        .WithMany("Values")
                        .HasForeignKey("CustomFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paper.Web.Data.Document", "Document")
                        .WithMany("CustomFields")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomField");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Paper.Web.Data.Correspondent", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Paper.Web.Data.Document", b =>
                {
                    b.Navigation("CustomFields");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Paper.Web.Data.DocumentType", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Paper.Web.Data.ShelfFolder", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Paper.Web.Data.Tag", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Paper.Web.Features.CustomFields.CustomField", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
